credentials:
  usernames:
  
    drgil:
      email: 
      name: Dr. Victor Gil
      password: $2b$12$Leu5cxYKzsAfzV5OZWQ9C.o8BbyDrX3dvtFhQTPEkOkdrNx1nbQaG

    drdelbos:
      email: victor.delbos@uic.es
      name: Victor DELBOS
      password: $2b$12$9RolNhH9ET3qw0ZEYeheieZuK1flhV7NTsAIgDWnRu05nBsVtiMyC

    paula:
      email: vdq@example.com
      name: Paula MARTIN
      password: $2b$12$wNGkFArOzhOt1Kr0TMrNO.Y7kIykIHCu6M.ueGrsWHMVbZKmPg0z.
      
    test:
      email: vdq@example.com
      name: test
      password: $2b$12$G2DeYPgzfVt8b/4ETB/xaOjiswqtlrjEoEYlxgsc27b7OyfHKdjwC


    ines:
      email: vdq@example.com
      name: Ines Gourgouillat
      password: $2b$12$KIi5d/yvfTx2RlOILOh6beAN/GDBR9NgYcmka1Olsl7uWgIjJq3za


cookie:
  name: lesionai_cookie
  key: somekey123
  expiry_days: 1

